### ISSUE TITLE
More signs for the 2.0 [EDIT]

### ISSUE THREAD

**Issue by SebastianTAPM** [Tim3Game/The-Expanded-Signs-Pack#2]
Hi, i want the Multipart signs back, i know they will exist in the future, but the issue is, i need special colors, ok so the blue an green are already on you todo right? but i need Brown and white too so could you make brown & white multipart and small signs?

**Comment by Tim3Game** [comment]
I can easily add a brown and white one, but they will work a bit differently by the sense of not being multiple one block signs but one big sign where you will add what you want, like a cake with topping. But could you please show me some example images of how they should look or in which country they can be founded, that would help me a lot.

**Comment by SebastianTAPM** [comment]
ok, so i wasnt expecting that fast response, you are amazing :smile: ok i will send images of what they should look, could you give me a contact address? (discord, mail or whataever) for send in the images

**Comment by Tim3Game** [comment]
You can try finding me as **Ťim3Game#1708** on Discord or if you on the **MTS Discord Server** there. If they some generic sings that would not identify your location, you can simply post them in this **Issue**.

**Comment by SebastianTAPM** [comment]
![mixej1](https://user-images.githubusercontent.com/46055485/101294540-b7333100-37f6-11eb-8125-60504349eca1.jpeg)
![cafeej2](https://user-images.githubusercontent.com/46055485/101294541-b9958b00-37f6-11eb-8412-333e32382b3f.png)
![cafeej1](https://user-images.githubusercontent.com/46055485/101294542-bac6b800-37f6-11eb-8139-44c13c9fd7fd.png)
![cafe1](https://user-images.githubusercontent.com/46055485/101294544-bbf7e500-37f6-11eb-8e5d-82a3bd48ca6b.png)
so there are all the examples, and i need all those sizes, if you were so kind to do all these sizes for the original blue and green colours i will be so grateful... oh, and the white colours i couldnt find any real life photos to them, but they are like poland ones like thes:
![image](https://user-images.githubusercontent.com/46055485/101294601-450f1c00-37f7-11eb-9497-1e9fb857ea31.png)
and i need them of all sizes too...
thanks

**Comment by Tim3Game** [comment]
It will take some time to design them but I will try to make them as soon as possible but I can't promise anything.

**Comment by SebastianTAPM** [comment]
> It will take some time to design them but I will try to make them as soon as possible but I can't promise anything.

Thanks, and hopefuly i will be able to make real highways with realistic big signs, thanks A LOT
